export interface IndustrialRecord {
    id: string;
    companyName: string;
    type: 'transporter' | 'supplier' | 'finance' | 'driver' | 'warehouse' | 'associate' | 'partner';
    category: string;
    industrial_category?: string;
    contactPerson: string;
    email: string;
    phone: string;
    mobile?: string;
    website: string;
    address: string;
    province: string;
    city: string;
    suburb?: string;
    minedServiceWording: string;
    vouchCount?: number;
    isClaimed?: boolean;
    marketingManager?: { name?: string; email?: string; mobile?: string };
    ceo?: { name?: string; email?: string; mobile?: string };
    sourceCollection?: string;
    createdAt?: string;
    updatedAt?: string;
}

export const DEFAULT_INDUSTRIAL_RECORDS: IndustrialRecord[] = [
    // --- TRANSPORTERS & HAULIERS ---
    {
        id: 'trans-001',
        companyName: 'Imperial Logistics South Africa',
        type: 'transporter',
        category: 'General Freight',
        industrial_category: 'General Freight',
        contactPerson: 'Kobus Venter',
        email: 'info@imperiallogistics.co.za',
        phone: '+27 11 373 9000',
        mobile: '+27 82 441 9012',
        website: 'https://www.imperiallogistics.co.za',
        address: 'Jeppestown, Johannesburg, Gauteng',
        province: 'Gauteng',
        city: 'Johannesburg',
        suburb: 'Jeppestown',
        minedServiceWording: 'Full-spectrum road freight, long-haul primary distribution, FMCG container transport and cold chain logistics across Southern Africa.',
        vouchCount: 14,
        isClaimed: true,
        ceo: { name: 'Mohammed Akoojee', email: 'm.akoojee@imperiallogistics.co.za', mobile: '+27 82 990 1200' },
        marketingManager: { name: 'Kobus Venter', email: 'k.venter@imperiallogistics.co.za', mobile: '+27 82 441 9012' }
    },
    {
        id: 'trans-002',
        companyName: 'Super Group Freight & Logistics',
        type: 'transporter',
        category: 'Container Transport',
        industrial_category: 'Container Transport',
        contactPerson: 'Sipho Ndlovu',
        email: 'freight@supergroup.co.za',
        phone: '+27 11 523 3000',
        mobile: '+27 83 200 4581',
        website: 'https://www.supergroup.co.za',
        address: 'Sandton, Johannesburg, Gauteng',
        province: 'Gauteng',
        city: 'Johannesburg',
        suburb: 'Sandton',
        minedServiceWording: 'Intermodal container haulage, port drayage from Durban and Cape Town, and heavy long-distance fleet operations.',
        vouchCount: 19,
        isClaimed: true,
        ceo: { name: 'Peter Mountford', email: 'p.mountford@supergroup.co.za', mobile: '+27 82 110 9900' },
        marketingManager: { name: 'Sipho Ndlovu', email: 's.ndlovu@supergroup.co.za', mobile: '+27 83 200 4581' }
    },
    {
        id: 'trans-003',
        companyName: 'Grindrod Logistics & Intermodal',
        type: 'transporter',
        category: 'Bulk / Aggregates',
        industrial_category: 'Bulk / Aggregates',
        contactPerson: 'Devan Naidoo',
        email: 'logistics@grindrod.com',
        phone: '+27 31 304 1451',
        mobile: '+27 82 809 3321',
        website: 'https://www.grindrod.com',
        address: 'Maydon Wharf, Durban, KwaZulu-Natal',
        province: 'KwaZulu-Natal',
        city: 'Durban',
        suburb: 'Maydon Wharf',
        minedServiceWording: 'Specialized port logistics, side-tipper bulk minerals transport, container yard handling, and corridor freight solutions.',
        vouchCount: 22,
        isClaimed: true,
        ceo: { name: 'Xolani Mbambo', email: 'x.mbambo@grindrod.com', mobile: '+27 82 770 1122' },
        marketingManager: { name: 'Devan Naidoo', email: 'd.naidoo@grindrod.com', mobile: '+27 82 809 3321' }
    },
    {
        id: 'trans-004',
        companyName: 'Unitrans Supply Chain Solutions',
        type: 'transporter',
        category: 'General Freight',
        industrial_category: 'General Freight',
        contactPerson: 'Johan Marais',
        email: 'contact@unitrans.co.za',
        phone: '+27 11 928 2000',
        mobile: '+27 82 554 9011',
        website: 'https://www.unitrans.co.za',
        address: 'Isando, Kempton Park, Gauteng',
        province: 'Gauteng',
        city: 'Kempton Park',
        suburb: 'Isando',
        minedServiceWording: 'Dedicated contract mining freight, fuel tanker distribution, agricultural haulage, and specialized heavy fleet management.',
        vouchCount: 11,
        isClaimed: false,
        marketingManager: { name: 'Johan Marais', email: 'j.marais@unitrans.co.za', mobile: '+27 82 554 9011' }
    },
    {
        id: 'trans-005',
        companyName: 'Value Logistics & Express Depot',
        type: 'transporter',
        category: 'Refrigerated Containers',
        industrial_category: 'Refrigerated Containers',
        contactPerson: 'Pieter Du Plessis',
        email: 'info@value.co.za',
        phone: '+27 11 570 2000',
        mobile: '+27 83 912 3040',
        website: 'https://www.value.co.za',
        address: 'Elandsfontein, Germiston, Gauteng',
        province: 'Gauteng',
        city: 'Germiston',
        suburb: 'Elandsfontein',
        minedServiceWording: 'Temperature-controlled reefer fleet, refrigerated FMCG distribution, cold-chain cross-docking, and national express freight.',
        vouchCount: 16,
        isClaimed: true,
        ceo: { name: 'Steven Gottschalk', email: 's.gottschalk@value.co.za', mobile: '+27 82 330 0011' }
    },
    {
        id: 'trans-006',
        companyName: 'Cross Border Hauliers RSA',
        type: 'transporter',
        category: 'Abnormal Loads',
        industrial_category: 'Abnormal Loads',
        contactPerson: 'Gideon Swart',
        email: 'operations@crossborderhauliers.co.za',
        phone: '+27 15 534 0980',
        mobile: '+27 82 770 4490',
        website: 'https://www.crossborderhauliers.co.za',
        address: 'Musina Industrial Hub, Limpopo',
        province: 'Limpopo',
        city: 'Musina',
        suburb: 'Industrial Hub',
        minedServiceWording: 'SADC corridor transport, heavy low-bed abnormal load permits, mining machinery relocation, and Beitbridge border clearance haulage.',
        vouchCount: 8,
        isClaimed: false
    },
    {
        id: 'trans-007',
        companyName: 'KLL Cold Chain Express',
        type: 'transporter',
        category: 'Refrigerated Containers',
        industrial_category: 'Refrigerated Containers',
        contactPerson: 'David Coetzee',
        email: 'dispatch@klllogistics.co.za',
        phone: '+27 21 951 8800',
        mobile: '+27 82 660 1198',
        website: 'https://www.klllogistics.co.za',
        address: 'Epping Industrial, Cape Town, Western Cape',
        province: 'Western Cape',
        city: 'Cape Town',
        suburb: 'Epping',
        minedServiceWording: 'Perishable produce export transport, refrigerated interlink fleet, fruit seasonal harvest haulage to Table Bay port terminal.',
        vouchCount: 12,
        isClaimed: true
    },
    {
        id: 'trans-008',
        companyName: 'Trencor Intermodal Haulage',
        type: 'transporter',
        category: 'Container Transport',
        industrial_category: 'Container Transport',
        contactPerson: 'Bongani Khumalo',
        email: 'transfers@trencor.co.za',
        phone: '+27 41 405 2100',
        mobile: '+27 83 400 9088',
        website: 'https://www.trencor.co.za',
        address: 'Deal Party, Gqeberha, Eastern Cape',
        province: 'Eastern Cape',
        city: 'Gqeberha',
        suburb: 'Deal Party',
        minedServiceWording: 'Port of Ngqura and Gqeberha harbor container transfers, automotive parts transport, and ISO tank container shipping.',
        vouchCount: 9,
        isClaimed: false
    },

    // --- SUPPLIERS ---
    {
        id: 'supp-001',
        companyName: 'Engen Industrial Fuel & Lubricants',
        type: 'supplier',
        category: 'Diesel',
        industrial_category: 'Diesel',
        contactPerson: 'Johann Van Zyl',
        email: 'johann.vanzyl@engen.co.za',
        phone: '+27 11 800 2100',
        mobile: '+27 82 555 0192',
        website: 'https://www.engen.co.za',
        address: 'Cape Town, Western Cape',
        province: 'Western Cape',
        city: 'Cape Town',
        suburb: 'Foreshore',
        minedServiceWording: 'Bulk commercial diesel 50ppm delivery, heavy vehicle lubricants, fleet fuel management cards and automated depot tank installations.',
        vouchCount: 25,
        isClaimed: true,
        marketingManager: { name: 'Johann Van Zyl', email: 'johann.vanzyl@engen.co.za', mobile: '+27 82 555 0192' }
    },
    {
        id: 'supp-002',
        companyName: 'Goodyear Tyres South Africa',
        type: 'supplier',
        category: 'Tyres',
        industrial_category: 'Tyres',
        contactPerson: 'Thabo Mokoena',
        email: 'thabo.mokoena@goodyear.co.za',
        phone: '+27 11 392 4100',
        mobile: '+27 83 411 9022',
        website: 'https://www.goodyear.co.za',
        address: 'Jet Park, Boksburg, Gauteng',
        province: 'Gauteng',
        city: 'Boksburg',
        suburb: 'Jet Park',
        minedServiceWording: 'Heavy commercial truck tyres, retreading casing services, mobile fleet tyre pressure monitoring systems and breakdown support.',
        vouchCount: 18,
        isClaimed: true
    },
    {
        id: 'supp-003',
        companyName: 'Scania Southern Africa Parts & Service',
        type: 'supplier',
        category: 'Truck Parts',
        industrial_category: 'Truck Parts',
        contactPerson: 'Mark Botha',
        email: 'mark.botha@scania.co.za',
        phone: '+27 11 661 9600',
        mobile: '+27 82 901 3320',
        website: 'https://www.scania.com/za',
        address: 'Aeroton, Johannesburg, Gauteng',
        province: 'Gauteng',
        city: 'Johannesburg',
        suburb: 'Aeroton',
        minedServiceWording: 'Genuine OEM Scania truck spare parts, reconditioned V8 diesel engines, gearbox assemblies, differential units and workshop diagnostics.',
        vouchCount: 30,
        isClaimed: true
    },
    {
        id: 'supp-004',
        companyName: 'Barloworld Equipment & Fleet Spares',
        type: 'supplier',
        category: 'Engine Refurbish',
        industrial_category: 'Engine Refurbish',
        contactPerson: 'Sipho Dlamini',
        email: 'sipho.dlamini@barloworld-equipment.com',
        phone: '+27 11 929 0000',
        mobile: '+27 82 334 1120',
        website: 'https://www.barloworld-equipment.com',
        address: 'Isando, Kempton Park, Gauteng',
        province: 'Gauteng',
        city: 'Kempton Park',
        suburb: 'Isando',
        minedServiceWording: 'Caterpillar diesel engine overhaul, hydraulic pump refurbishing, earthmoving spares, filter replacement kits and heavy component testing.',
        vouchCount: 21,
        isClaimed: true
    },
    {
        id: 'supp-005',
        companyName: 'Bult Trailers & Component Supplies',
        type: 'supplier',
        category: 'Trailer repairs',
        industrial_category: 'Trailer repairs',
        contactPerson: 'Kobus Marais',
        email: 'kobus.marais@bulttrailers.co.za',
        phone: '+27 12 541 2000',
        mobile: '+27 82 771 0044',
        website: 'https://www.bulttrailers.co.za',
        address: 'Rosslyn Industrial, Pretoria, Gauteng',
        province: 'Gauteng',
        city: 'Pretoria',
        suburb: 'Rosslyn',
        minedServiceWording: 'Custom interlink side-tipper manufacturing, trailer brake re-lining, BPW axle spares, fifth-wheel kingpin replacements and tarpaulins.',
        vouchCount: 15,
        isClaimed: false
    },
    {
        id: 'supp-006',
        companyName: 'TotalEnergies Commercial RSA',
        type: 'supplier',
        category: 'Oils & Lubricants',
        industrial_category: 'Oils & Lubricants',
        contactPerson: 'Claire Bennett',
        email: 'lubricants.rsa@totalenergies.com',
        phone: '+27 11 778 2000',
        mobile: '+27 82 991 0088',
        website: 'https://www.totalenergies.co.za',
        address: 'Rosebank, Johannesburg, Gauteng',
        province: 'Gauteng',
        city: 'Johannesburg',
        suburb: 'Rosebank',
        minedServiceWording: 'Heavy duty Rubia engine oils, synthetic transmission fluids, bulk industrial grease supply and fleet oil analysis programs.',
        vouchCount: 14,
        isClaimed: true
    },
    {
        id: 'supp-007',
        companyName: 'Cummins Africa Diesel Solutions',
        type: 'supplier',
        category: 'Turbo',
        industrial_category: 'Turbo',
        contactPerson: 'Andrew Smith',
        email: 'africa.sales@cummins.com',
        phone: '+27 11 321 8700',
        mobile: '+27 83 220 1109',
        website: 'https://www.cummins.com/africa',
        address: 'Waterfall City, Midrand, Gauteng',
        province: 'Gauteng',
        city: 'Midrand',
        suburb: 'Waterfall City',
        minedServiceWording: 'Holset turbochargers, fuel injector reconditioning, Cummins ISX/ISM engine spares, electronic control modules and power generators.',
        vouchCount: 17,
        isClaimed: true
    },

    // --- CAPITAL & FINANCE ---
    {
        id: 'fin-001',
        companyName: 'Absa Commercial Vehicle & Asset Finance',
        type: 'finance',
        category: 'Asset Finance',
        industrial_category: 'Asset Finance',
        contactPerson: 'Nkosana Mthembu',
        email: 'assetfinance@absa.co.za',
        phone: '+27 11 350 4000',
        mobile: '+27 82 400 1190',
        website: 'https://www.absa.co.za',
        address: 'Sandton, Johannesburg, Gauteng',
        province: 'Gauteng',
        city: 'Johannesburg',
        suburb: 'Sandton',
        minedServiceWording: 'Heavy commercial vehicle installment sale agreements, fleet refinancing options, trailer lease packages and residual value structuring.',
        vouchCount: 28,
        isClaimed: true
    },
    {
        id: 'fin-002',
        companyName: 'Standard Bank Fleet & Capital Finance',
        type: 'finance',
        category: 'Working Capital',
        industrial_category: 'Working Capital',
        contactPerson: 'Tariq Cassim',
        email: 'fleetfinance@standardbank.co.za',
        phone: '+27 11 636 9111',
        mobile: '+27 83 901 2288',
        website: 'https://www.standardbank.co.za',
        address: 'Rosebank, Johannesburg, Gauteng',
        province: 'Gauteng',
        city: 'Johannesburg',
        suburb: 'Rosebank',
        minedServiceWording: 'Fuel bridging facilities, freight invoice discounting, trade working capital, commercial vehicle insurance and telematics integration.',
        vouchCount: 31,
        isClaimed: true
    },
    {
        id: 'fin-003',
        companyName: 'Nedbank Corporate Logistics Capital',
        type: 'finance',
        category: 'Debt Funders',
        industrial_category: 'Debt Funders',
        contactPerson: 'Annelize Van Der Merwe',
        email: 'corpfinance@nedbank.co.za',
        phone: '+27 11 294 4444',
        mobile: '+27 82 331 9081',
        website: 'https://www.nedbank.co.za',
        address: 'Sandton, Johannesburg, Gauteng',
        province: 'Gauteng',
        city: 'Johannesburg',
        suburb: 'Sandton',
        minedServiceWording: 'Structured senior debt for fleet expansion, warehouse infrastructure financing, cross-border trade funding and ESG fleet green loans.',
        vouchCount: 20,
        isClaimed: true
    },
    {
        id: 'fin-004',
        companyName: 'WesBank Commercial Freight Finance',
        type: 'finance',
        category: 'Asset Finance',
        industrial_category: 'Asset Finance',
        contactPerson: 'Charl Pretorius',
        email: 'commercial@wesbank.co.za',
        phone: '+27 11 632 6000',
        mobile: '+27 82 119 4022',
        website: 'https://www.wesbank.co.za',
        address: 'Fairland, Johannesburg, Gauteng',
        province: 'Gauteng',
        city: 'Johannesburg',
        suburb: 'Fairland',
        minedServiceWording: 'Heavy truck financing, trailer fleet leasing, Yellow Metal earthmoving loans, and operating lease contracts with maintenance plans.',
        vouchCount: 27,
        isClaimed: true
    },
    {
        id: 'fin-005',
        companyName: 'Invicta Capital Logistics Fund',
        type: 'finance',
        category: 'Niche Lenders',
        industrial_category: 'Niche Lenders',
        contactPerson: 'Suresh Pillay',
        email: 'info@invictacapital.co.za',
        phone: '+27 11 620 1500',
        mobile: '+27 83 700 9110',
        website: 'https://www.invictacapital.co.za',
        address: 'Germiston Industrial, Gauteng',
        province: 'Gauteng',
        city: 'Germiston',
        suburb: 'Southfield',
        minedServiceWording: 'Mezzanine funding for mid-tier transport operators, short-term load funding, diesel purchase credit facilities, and fleet sale-and-leaseback.',
        vouchCount: 13,
        isClaimed: false
    },
    {
        id: 'fin-006',
        companyName: 'Santam Heavy Haulage Risk & Insurance',
        type: 'finance',
        category: 'Insurance',
        industrial_category: 'Insurance',
        contactPerson: 'Mariska Louw',
        email: 'commercial.claims@santam.co.za',
        phone: '+27 21 915 7000',
        mobile: '+27 82 881 0033',
        website: 'https://www.santam.co.za',
        address: 'Bellville, Cape Town, Western Cape',
        province: 'Western Cape',
        city: 'Cape Town',
        suburb: 'Bellville',
        minedServiceWording: 'Comprehensive goods-in-transit (GIT) coverage, commercial fleet accidental damage insurance, cross-border transit liability and environmental spill cover.',
        vouchCount: 22,
        isClaimed: true
    },

    // --- HUMAN CAPITAL & DRIVERS ---
    {
        id: 'driver-001',
        companyName: 'South African Heavy Vehicle Drivers Guild',
        type: 'driver',
        category: 'Code 14 Drivers',
        industrial_category: 'Code 14 Drivers',
        contactPerson: 'Siphamandla Zondi',
        email: 'drivers@saguild.co.za',
        phone: '+27 11 834 1200',
        mobile: '+27 82 990 4110',
        website: 'https://www.saguild.co.za',
        address: 'Braamfontein, Johannesburg, Gauteng',
        province: 'Gauteng',
        city: 'Johannesburg',
        suburb: 'Braamfontein',
        minedServiceWording: 'Verified Code 14 (EC1) heavy interlink driver placement pool, PrDP compliance cleared, long-haul cross-border experience.',
        vouchCount: 10,
        isClaimed: true
    },
    {
        id: 'driver-002',
        companyName: 'Translogistics Certified Mechanics Pool',
        type: 'driver',
        category: 'Mechanic',
        industrial_category: 'Mechanic',
        contactPerson: 'Wayne Peterson',
        email: 'mechanics@translogistics.co.za',
        phone: '+27 31 205 9000',
        mobile: '+27 83 221 0098',
        website: 'https://www.translogistics.co.za',
        address: 'Pinetown, Durban, KwaZulu-Natal',
        province: 'KwaZulu-Natal',
        city: 'Durban',
        suburb: 'Pinetown',
        minedServiceWording: 'Trade-tested heavy diesel mechanics, mobile roadside diagnostic technicians, transmission rebuild specialists for Volvo and Mercedes fleets.',
        vouchCount: 14,
        isClaimed: false
    },

    // --- WAREHOUSES & HUBS ---
    {
        id: 'wh-001',
        companyName: 'City Deep Container Logistics Depot',
        type: 'warehouse',
        category: 'Container Yard',
        industrial_category: 'Container Yard',
        contactPerson: 'Lindiwe Dube',
        email: 'depot@citydeep.co.za',
        phone: '+27 11 613 8000',
        mobile: '+27 82 110 5890',
        website: 'https://www.citydeepdepot.co.za',
        address: 'City Deep, Johannesburg, Gauteng',
        province: 'Gauteng',
        city: 'Johannesburg',
        suburb: 'City Deep',
        minedServiceWording: 'Inland dry container depot, reach-stacker container lifting, customs bonded warehouse, break-bulk destuffing and rail siding connections.',
        vouchCount: 17,
        isClaimed: true
    },
    {
        id: 'wh-002',
        companyName: 'Durban Cold Storage & Logistics Hub',
        type: 'warehouse',
        category: 'Cold Storage',
        industrial_category: 'Cold Storage',
        contactPerson: 'Faizel Patel',
        email: 'coldstore@durbanhub.co.za',
        phone: '+27 31 465 1100',
        mobile: '+27 83 400 1192',
        website: 'https://www.durbanhub.co.za',
        address: 'Maydon Wharf, Durban, KwaZulu-Natal',
        province: 'KwaZulu-Natal',
        city: 'Durban',
        suburb: 'Maydon Wharf',
        minedServiceWording: 'Port-side temperature controlled cold store (-25C to +15C), citrus export inspection bay, blast freezing and pallet storage.',
        vouchCount: 23,
        isClaimed: true
    }
];
